<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>ColorfulUI</AssemblyName>
    <RootNamespace>ColorfulUI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Colors\*.png" />
  </ItemGroup>

</Project>
